"""PDF report generator using fpdf2."""

from datetime import datetime
from pathlib import Path

from fpdf import FPDF

from ai_tax_prep.export.templates import (
    DISCLAIMER_HEADER,
    REPORT_TITLE,
    WATERMARK_TEXT,
    build_credits_section,
    build_deduction_section,
    build_income_section,
    build_personal_section,
    build_rates_section,
    build_refund_section,
    build_tax_section,
)


class TaxReportPDF(FPDF):
    """Custom PDF class for tax reports."""

    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.cell(0, 10, REPORT_TITLE, new_x="LMARGIN", new_y="NEXT", align="C")
        self.set_font("Helvetica", "", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 5, WATERMARK_TEXT, new_x="LMARGIN", new_y="NEXT", align="C")
        self.set_text_color(0, 0, 0)
        self.ln(5)

    def footer(self):
        self.set_y(-25)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(150, 150, 150)
        self.cell(0, 4, "FOR INFORMATIONAL PURPOSES ONLY -NOT FOR FILING", align="C", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 4, f"Generated by AI Tax Prep Assistant on {datetime.now().strftime('%Y-%m-%d %H:%M')}", align="C", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 4, f"Page {self.page_no()}/{{nb}}", align="C")

    def add_section(self, title: str, rows: list[tuple[str, str]]):
        """Add a section with a title and key-value rows."""
        self.set_font("Helvetica", "B", 12)
        self.set_fill_color(240, 240, 240)
        self.cell(0, 8, f"  {title}", fill=True, new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

        self.set_font("Helvetica", "", 10)
        for label, value in rows:
            if not label and not value:
                self.ln(2)
                continue
            self.cell(110, 6, f"  {label}", new_x="RIGHT")
            # Bold for totals
            if "TOTAL" in label.upper() or "refund" in label.lower():
                self.set_font("Helvetica", "B", 10)
            self.cell(0, 6, value, new_x="LMARGIN", new_y="NEXT")
            self.set_font("Helvetica", "", 10)

        self.ln(3)

    def add_disclaimer(self):
        """Add the disclaimer section."""
        self.ln(5)
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(180, 0, 0)
        self.cell(0, 5, "DISCLAIMER", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 8)
        self.set_text_color(100, 100, 100)
        self.multi_cell(0, 4, DISCLAIMER_HEADER)
        self.set_text_color(0, 0, 0)

    def add_suggestions(self, suggestions: list[dict]):
        """Add deduction/credit suggestions section."""
        applicable = [s for s in suggestions if s.get("applies") is True]
        possible = [s for s in suggestions if s.get("applies") is None]

        if not applicable and not possible:
            return

        self.set_font("Helvetica", "B", 12)
        self.set_fill_color(240, 240, 240)
        self.cell(0, 8, "  Deduction & Credit Opportunities", fill=True, new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

        if applicable:
            self.set_font("Helvetica", "B", 10)
            self.cell(0, 6, "  Applicable:", new_x="LMARGIN", new_y="NEXT")
            self.set_font("Helvetica", "", 9)
            for s in applicable:
                value = f" (est. {s['estimated_value']:,.0f})" if s.get("estimated_value") else ""
                self.multi_cell(0, 5, f"    - {s['name']}{value}: {s['explanation']}")
                self.ln(1)

        if possible:
            self.set_font("Helvetica", "B", 10)
            self.cell(0, 6, "  Worth Investigating:", new_x="LMARGIN", new_y="NEXT")
            self.set_font("Helvetica", "", 9)
            for s in possible:
                self.multi_cell(0, 5, f"    - {s['name']}: {s['explanation']}")
                self.ln(1)

    def add_explanation(self, text: str):
        """Add LLM-generated plain-English explanation."""
        self.set_font("Helvetica", "B", 12)
        self.set_fill_color(240, 240, 240)
        self.cell(0, 8, "  Summary", fill=True, new_x="LMARGIN", new_y="NEXT")
        self.ln(2)
        self.set_font("Helvetica", "", 10)
        self.multi_cell(0, 5, text)
        self.ln(3)


def generate_report(
    result: dict,
    output_path: str | Path,
    explanation: str = "",
) -> Path:
    """Generate a PDF tax report.

    Args:
        result: Tax calculation result dict
        output_path: Where to save the PDF
        explanation: Optional LLM-generated explanation text

    Returns:
        Path to the generated PDF
    """
    output_path = Path(output_path)

    pdf = TaxReportPDF()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=30)
    pdf.add_page()

    # Sections
    pdf.add_section("Personal Information", build_personal_section(result))
    pdf.add_section("Income", build_income_section(result))
    pdf.add_section("Deductions", build_deduction_section(result))
    pdf.add_section("Tax Calculation", build_tax_section(result))
    pdf.add_section("Credits", build_credits_section(result))
    pdf.add_section("Payments & Refund", build_refund_section(result))
    pdf.add_section("Effective Tax Rates", build_rates_section(result))

    # Suggestions
    suggestions = result.get("deduction_credit_suggestions", [])
    if suggestions:
        pdf.add_suggestions(suggestions)

    # Plain-English explanation
    if explanation:
        pdf.add_explanation(explanation)

    # Disclaimer
    pdf.add_disclaimer()

    # Save
    pdf.output(str(output_path))
    return output_path
