"""Report section templates and disclaimer text for PDF export."""

REPORT_TITLE = "Tax Preparation Summary Report"

DISCLAIMER_HEADER = (
    "IMPORTANT DISCLAIMER: This report is generated by TaxSight for "
    "informational and educational purposes only. It is NOT professional tax advice, "
    "NOT a substitute for a licensed tax preparer or CPA, and should NOT be used for "
    "official tax filing with the IRS or any state tax authority. Consult a qualified "
    "tax professional for your specific situation."
)

WATERMARK_TEXT = "FOR INFORMATIONAL PURPOSES ONLY -NOT FOR FILING"


def format_currency(amount: float) -> str:
    """Format a dollar amount."""
    if amount < 0:
        return f"-${abs(amount):,.2f}"
    return f"${amount:,.2f}"


def format_percentage(rate: float) -> str:
    """Format a percentage."""
    return f"{rate:.1f}%"


def build_personal_section(result: dict) -> list[tuple[str, str]]:
    """Build personal info section rows."""
    return [
        ("Tax Year", str(result.get("tax_year", ""))),
        ("Filing Status", result.get("filing_status", "").replace("_", " ").title()),
        ("State of Residence", result.get("state", "")),
    ]


def build_income_section(result: dict) -> list[tuple[str, str]]:
    """Build income section rows."""
    rows = [
        ("Total Gross Income", format_currency(result.get("total_gross_income", 0))),
        ("Adjusted Gross Income (AGI)", format_currency(result.get("agi", 0))),
        ("Taxable Income", format_currency(result.get("taxable_income", 0))),
    ]
    return rows


def build_deduction_section(result: dict) -> list[tuple[str, str]]:
    """Build deductions section rows."""
    rows = [
        ("Deduction Method", "Itemized" if result.get("itemizes") else "Standard"),
        ("Standard Deduction", format_currency(result.get("standard_deduction", 0))),
    ]
    if result.get("itemizes"):
        rows.append(("Itemized Deductions Total", format_currency(result.get("itemized_total", 0))))
    return rows


def build_tax_section(result: dict) -> list[tuple[str, str]]:
    """Build tax calculation section rows."""
    se_detail = result.get("se_tax_detail", {})
    rows = [
        ("Federal Income Tax", format_currency(result.get("federal_income_tax", 0))),
    ]
    if se_detail.get("total_se_tax", 0) > 0:
        rows.append(("Self-Employment Tax", format_currency(se_detail["total_se_tax"])))
    rows.extend([
        ("Total Federal Tax", format_currency(result.get("total_federal_tax", 0))),
        ("State Income Tax", format_currency(result.get("state_income_tax", 0))),
    ])
    return rows


def build_credits_section(result: dict) -> list[tuple[str, str]]:
    """Build credits section rows."""
    rows = []
    if result.get("eitc", 0) > 0:
        rows.append(("Earned Income Tax Credit", format_currency(result["eitc"])))
    if result.get("child_tax_credit", 0) > 0:
        rows.append(("Child Tax Credit", format_currency(result["child_tax_credit"])))
    if not rows:
        rows.append(("No credits applied", ""))
    return rows


def build_refund_section(result: dict) -> list[tuple[str, str]]:
    """Build payments & refund section rows."""
    rows = [
        ("Federal Withholding", format_currency(result.get("federal_withholding", 0))),
        ("Estimated Federal Payments", format_currency(result.get("estimated_federal_payments", 0))),
        ("State Withholding", format_currency(result.get("state_withholding", 0))),
        ("", ""),
    ]

    federal_ro = result.get("federal_refund_or_owed", 0)
    state_ro = result.get("state_refund_or_owed", 0)
    total_ro = result.get("total_refund_or_owed", 0)

    rows.append((
        "Federal Refund / (Amount Owed)",
        format_currency(federal_ro),
    ))
    rows.append((
        "State Refund / (Amount Owed)",
        format_currency(state_ro),
    ))
    rows.append((
        "TOTAL REFUND / (AMOUNT OWED)",
        format_currency(total_ro),
    ))

    return rows


def build_rates_section(result: dict) -> list[tuple[str, str]]:
    """Build effective rates section rows."""
    return [
        ("Effective Federal Rate", format_percentage(result.get("effective_federal_rate", 0))),
        ("Effective State Rate", format_percentage(result.get("effective_state_rate", 0))),
        ("Effective Total Rate", format_percentage(result.get("effective_total_rate", 0))),
    ]
